#!/bin/bash
# Will be executed as user "root".

# Replace-Variables
PLUGINNAME=REPLACELBPPLUGINDIR
LBPCONFIGDIR=REPLACELBPCONFIGDIR
LBPHTMLAUTHDIR=REPLACELBPHTMLAUTHDIR
LBPLOGDIR=REPLACELBPLOGDIR

# Source logging library and iniparser
. $LBHOMEDIR/libs/bashlib/loxberry_log.sh
. $LBHOMEDIR/libs/bashlib/iniparser.sh

PACKAGE=$PLUGINNAME
NAME=Daemon
FILENAME=$LBPLOGDIR/daemon.log
#LOGLEVEL=7

LOGSTART "DAEMON Script from Stats4Lox Plugin"

# Use correct rrdcached settings
if [ ! -L /etc/default/rrdcached ]; then
  LOGINF "Re-linking rrdcached settings file"
  mv /etc/default/rrdcached /etc/default/rrdcached.old
  ln -s $LBPCONFIGDIR/rrdcached /etc/default/rrdcached
  /usr/sbin/service rrdcached restart
fi

LOGEND "Daemon finished"

# Finished
exit 0
