#!/bin/bash

# Will be executed as user "root".

# Name this file "daemon.sh" in your plugin-archive. It will be renamed to NAME
# during installation

pluginname=$(basename $0 .sh)

if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$pluginname - DAEMON Script from Stats4Lox Plugin"
fi

# Use correct rrdcached settings
if [ ! -L /etc/default/rrdcached ]; then
  mv /etc/default/rrdcached /etc/default/rrdcached.old
  ln -s REPLACEINSTALLFOLDER/config/plugins/REPLACEFOLDERNAME/rrdcached /etc/default/rrdcached
  /usr/sbin/service rrdcached restart
fi

if [ ! -L REPLACEINSTALLFOLDER/log/plugins/REPLACEFOLDERNAME/stats4lox.log ]; then
  timestamp=$(date +%s)
  mv REPLACEINSTALLFOLDER/log/plugins/REPLACEFOLDERNAME/stats4lox.log REPLACEINSTALLFOLDER/log/plugins/REPLACEFOLDERNAME/stats4lox.log.$timestamp
fi

touch /run/shm/REPLACEFOLDERNAME/stats4lox.log 
chown loxberry.loxberry /run/shm/REPLACEFOLDERNAME/stats4lox.log 
ln -s /run/shm/REPLACEFOLDERNAME/stats4lox.log REPLACEINSTALLFOLDER/log/plugins/REPLACEFOLDERNAME/stats4lox.log

exit 0
