{
 "title": "Neuer Test",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Puffer Zone 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "0002:value", "type": "timeserie" }
   ]
  },
  {
   "title": "Außentemperatur",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "0001:value", "type": "timeserie" }
   ]
  },
  {
   "title": "TV-Raum-Temperatur",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "0005:value", "type": "timeserie" }
   ]
  }
 ]
}